perfil:
    pattern:  /
    defaults: { _controller: "UsuarioBundle:Perfil:index" }

perfil_show:
    pattern:  /{id}/show
    defaults: { _controller: "UsuarioBundle:Perfil:show" }

perfil_new:
    pattern:  /new
    defaults: { _controller: "UsuarioBundle:Perfil:new" }

perfil_create:
    pattern:  /create
    defaults: { _controller: "UsuarioBundle:Perfil:create" }
    requirements: { _method: post }

perfil_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UsuarioBundle:Perfil:edit" }

perfil_update:
    pattern:  /{id}/update
    defaults: { _controller: "UsuarioBundle:Perfil:update" }
    requirements: { _method: post }

perfil_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UsuarioBundle:Perfil:delete" }
    requirements: { _method: post }
    
perfil_restore:
    pattern:  /{id}/restore
    defaults: { _controller: "UsuarioBundle:Perfil:restore" }
    requirements: { _method: post }
