cliente:
    path:     /clientes
    defaults: { _controller: "AgpBundle:Cliente:index" }
cliente_show:
    path:     /{id}/show
    defaults: { _controller: "AgpBundle:Cliente:show" }

cliente_new:
    path:     /new
    defaults: { _controller: "AgpBundle:Cliente:new" }

cliente_create:
    path:     /create
    defaults: { _controller: "AgpBundle:Cliente:create" }
    requirements: { _method: post }

cliente_create_ajax:
    path:     /createajax
    defaults: { _controller: "AgpBundle:Cliente:createAjax" }
    requirements: { _method: post }

cliente_edit:
    path:     /{id}/edit
    defaults: { _controller: "AgpBundle:Cliente:edit" }

cliente_update:
    path:     /{id}/update
    defaults: { _controller: "AgpBundle:Cliente:update" }
    requirements: { _method: post|put }

cliente_delete:
    path:     /{id}/delete
    defaults: { _controller: "AgpBundle:Cliente:delete" }
    requirements: { _method: post|delete }
