<?php

namespace JGM\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaginaInicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaginaInicioRepository extends EntityRepository
{
    
}